services:
  db:
    image: mysql:latest
    container_name: container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - db:/var/lib/mysql
volumes:
  db: