version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gym_buddy
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/initiate.sql:/docker-entrypoint-initdb.d/initiate.sql

volumes:
  db_data:
